version: '3'

services:
  app:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=443
      - LOCALE=fr
      - SIGNATURE=$2a$10$gTEKbwT/YCFo1HMRb7m2COAxe2uxGKA.n.4JqnTR6WdWf0o4Ppzua
      - SECRET=6fsY4I9XDvrzZkdE5L5vbvBJpmMZ6GSEVt5EVGYvBXE4vu5BpgqQyfuBdObE
      - MONGO_URI=mongodb://database/
      - MONGO_USERS_COLLECTION=users
    ports:
      - 8585:8585
    restart: always

  database:
    image: mongo
    restart: always
