version: '3'

services:
  app:
    build: ./app
    ports:
      - 8585:8585
    environment:
      - PORT=8585
      - MONGO_URI=mongodb://database/rtype
      - SIGNATURE=$$2a$$10$$gTEKbwT/YCFo1HMRb7m2COAxe2uxGKA.n.4JqnTR6WdWf0o4Ppzua
      - SECRET=6fsY4I9XDvrzZkdE5L5vbvBJpmMZ6GSEVt5EVGYvBXE4vu5BpgqQyfuBdObE
      - MAILER_USER=unity.shikalegend@gmail.com
      - MAILER_PASS=234567890
    volumes:
      - ./database/data/db:/data/db
      - ./database/data/configdb:/data/configdb
    restart: always

  database:
    image: mongo
    restart: always
